<?php

namespace AppBundle\Repository;

/**
 * DostawaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DostawaRepository extends \Doctrine\ORM\EntityRepository
{
}
