<?php

namespace AppBundle\Repository;

/**
 * KarmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KarmaRepository extends \Doctrine\ORM\EntityRepository
{
}
