<?php

namespace AppBundle\Repository;

/**
 * MagazynRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazynRepository extends \Doctrine\ORM\EntityRepository
{
}
