<?php

namespace AppBundle\Repository;

/**
 * TerrariumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrariumRepository extends \Doctrine\ORM\EntityRepository
{
}
