<?php

namespace AppBundle\Repository;

/**
 * TypZdarzeniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypZdarzeniaRepository extends \Doctrine\ORM\EntityRepository
{
}
