<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ZdarzenieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZdarzenieRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findBySession($session, $currentPage = 1, $limit) {
        $query = "SELECT z.id, t.nazwa as typZdarzenia, "
                . "CONCAT(p.imie,' ',p.nazwisko) as pracownik , pt.kodEan as ptasznik, z.data, z.opis"
                . " FROM AppBundle:Zdarzenie z "
                . "LEFT JOIN AppBundle:TypZdarzenia t WITH z.typZdarzenia=t.id"
                . " LEFT JOIN AppBundle:Pracownik p WITH z.pracownik=p.id"
                . " LEFT JOIN AppBundle:Ptasznik pt WITH z.ptasznik=pt.id";
        if ($session->get('find')) {
            $find = trim($session->get('find'));
            $query .= " WHERE pt.id LIKE '%$find%' OR "
                    . "pt.kodEan LIKE '%$find%' OR "
                    . "pt.nazwaLacinska LIKE '%$find%' OR "
                    . "pt.nazwaPolska LIKE '%$find%' OR "
                    . "pt.lpWPartii LIKE '%$find%' OR "
                    . "pt.uwagi LIKE '%$find%' OR "
                    . "pt.zakupRozmiar LIKE '%$find%' OR "
                    . "pt.aktualnyRozmiar LIKE '%$find%' OR "
                    . "pt.plec LIKE '%$find%' OR "
                    . "t.id LIKE '%$find%' OR "
                    . "t.nazwa LIKE '%$find%' OR "
                    . "t.opis LIKE '%$find%' OR "
                    . "p.id LIKE '%$find%' OR "
                    . "p.nazwisko LIKE '%$find%' OR "
                    . "p.imie LIKE '%$find%' OR "
                    . "p.nrTelefonu LIKE '%$find%' OR "
                    . "p.email LIKE '%$find%' OR "
                    . "p.stanowisko LIKE '%$find%' OR "
                    . "z.data LIKE '%$find%' OR "
                    . "z.opis LIKE '%$find%'"
                    ;
        }

        $query .= " ORDER BY z.data DESC, z.id DESC";
        $result = $this->getEntityManager()
                ->createQuery($query);

        $paginator = $this->paginate($result, $currentPage, $limit);

        return $paginator;
    }

    public function paginate($dql, $page = 1, $limit = 10) {
        $paginator = new Paginator($dql);
        $paginator->setUseOutputWalkers(false);

        $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1)) // Offset
                ->setMaxResults($limit); // Limit

        return $paginator;
    }
    
    
    public function findByIds($ids) {
        $query = "SELECT z.id, t.nazwa as typZdarzenia, "
                . "CONCAT(p.imie,' ',p.nazwisko) as pracownik , pt.kodEan as ptasznik, z.data, z.opis"
                . " FROM AppBundle:Zdarzenie z "
                . "LEFT JOIN AppBundle:TypZdarzenia t WITH z.typZdarzenia=t.id"
                . " LEFT JOIN AppBundle:Pracownik p WITH z.pracownik=p.id"
                . " LEFT JOIN AppBundle:Ptasznik pt WITH z.ptasznik=pt.id"
                . " WHERE ";
        $i = 0;
        $len = count($ids) - 1;
        foreach ($ids as $id) {
            $query .= "z.id = $id";
            if ($i < $len)
                $query .= " OR ";
            $i++;
        }
        

        return $this->getEntityManager()->createQuery($query)
                        ->getResult();
    }

}
