# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
         AppBundle\Entity\Pracownik:
             algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
             entity:
                 class: AppBundle:Pracownik
                 property: username
                 # if you're using multiple entity managers
                 # manager_name: customer

    firewalls:
        login_firewall:
             pattern:   ^/login$
             anonymous: ~
        register_firewall:
             pattern:   ^/register$
             anonymous: ~
        secured_area:
             pattern:    ^/
             form_login: ~
        # disables authentication for assets and the profiler, adapt it according to your needs
        default:
             pattern:    ^/
             http_basic: ~
             provider: our_db_provider
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login: 
                login_path: /login
                check_path: /login_check
    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }