<?php

namespace AppBundle\Entity;

/**
 * PracownikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracownikRepository extends \Doctrine\ORM\EntityRepository
{
}
